### ISSUE TITLE
Compilation error after #10

### ISSUE THREAD

**Issue by moononournation** [bitbank2/JPEGDEC#12]
After update to #10 the follow compilation error appear:
In file included from ~/Documents/Arduino/libraries/JPEGDEC/src/JPEGDEC.h:26:0,
                 from ~/Documents/Arduino/libraries/JPEGDEC/src/jpeg.c:23:
~/Documents/Arduino/hardware/espressif/esp32/libraries/FS/src/FS.h:24:18: fatal error: memory: No such file or directory
compilation terminated.

**Comment by bitbank2** [comment]
I just pushed a fix for other issues, but cannot reproduce the problem you're seeing with FS.h. Please do a git pull and see if it works now.

**Comment by moononournation** [comment]
checked same error message

**Comment by moononournation** [comment]
I am using Arduino IDE 1.8.13

**Comment by moononournation** [comment]
just checked it can fix if rename jpeg.c to jpeg.cpp

**Comment by bitbank2** [comment]
That sounds like a build issue. Are you using the Arduino IDE?

**Comment by moononournation** [comment]
I am using Arduino IDE 1.8.13 and the error only appear on ESP8266 and ESP32.
