### ISSUE TITLE
Is it possible to re-encode a smaller version of an image?

### ISSUE THREAD

**Issue by ambanmba** [bitbank2/JPEGDEC#16]
In my use case I'd like to send a smaller version of a particular image (it can be 300-400k). This file is sitting in SPIFFS and currently I send the whole image which takes about 30 seconds. I'd like to send a much smaller version.

**Comment by bitbank2** [comment]
I wasn't planning on making an Arduino JPEG encoder because it requires even more RAM and will limit which MCUs can use it.

**Comment by bitbank2** [comment]
I am nearly finished writing a JPEG encoder and it uses very little RAM and is quite fast. I will probably have something ready to test later this week.

**Comment by AlbertoLopSie** [comment]
> I am nearly finished writing a JPEG encoder and it uses very little RAM and is quite fast. I will probably have something ready to test later this week.

Hi!

I know it has passed som time but,  did you manage to write any encoding ?
