### ISSUE TITLE
JPEG rendering is wrong for odd dimension tiles.

### ISSUE THREAD

**Issue by prenticedavid** [bitbank2/JPEGDEC#21]
I displayed the example JPEGs on a 320x480 ST7796S screen on ESP32 target.
```
#include "../test_images/sciopero.h"
#include "../test_images/st_peters.h"
#include "../test_images/tulips.h"
```
`sciopero[]` is 300x300 which means 18 rows of 16x16 tiles.  Last row has 16x12 tiles.   This last row is corrupt.
`tulips[]` is 640x480 which means scale by 1/2 and perfect 16x16 tiles.   However the rendering is a little "blocky".   Observe the "sharkfin" shape of the green leaves.

If I display a 320x245 JPEG the bottom row of tiles is corrupt.

If I display your examples on a 240x320 ILI9341 screen,  they all require scaling.  However the blockiness is not so noticeable.
If I display a 250x315 JPEG all the tiles get corrupted.

Rendering JPEGs with Chan's tjpgd.c is much SLOWER but all the tiles are rendered correctly.

David.

**Comment by bitbank2** [comment]
"If I display a 250x315 JPEG all the tiles get corrupted". Are you scaling it or drawing it 1:1? Can you show me the code and a sample image?

**Comment by prenticedavid** [comment]
This is a 250x315 JPEG
![bapa_91](https://user-images.githubusercontent.com/17822093/121056410-137f0980-c7b6-11eb-9183-1c07fbee76a6.jpg)
This is a 320x245 JPEG
![testcard_320x245x24_md](https://user-images.githubusercontent.com/17822093/121056555-38737c80-c7b6-11eb-9ff0-07044a1b8dab.jpg)

This is my rendering function:   It adjusts rotation and scaling to suit the JPEG and screen dimensions.
```
void load_jpg_P(const uint8_t *arrayname, uint16_t array_size, const char* fn)
{
    long lTime;
    tft.fillScreen(0x0000); //TFT_BLACK
    if (jpeg.openFLASH((uint8_t *)arrayname, array_size, JPEGDraw))
    {
        lTime = micros();
        uint8_t scale = 0;
        int w = jpeg.getWidth(), h = jpeg.getHeight();
        uint8_t arg = 0;
        uint8_t rot = (w > h); //i.e. landscape
        if (tft.getRotation() != rot) tft.setRotation(rot);
        tft.startWrite(); // Not sharing TFT bus on PyPortal, just CS once and leave it
        for (scale = 0; scale < 3; scale++) {
            if ((w >> scale) <= tft.width() && (h >> scale) <= tft.height()) break;
        }
        arg = (1 << scale); // | JPEG_AUTO_ROTATE;
        if (jpeg.hasThumb()) arg = JPEG_EXIF_THUMBNAIL;
        if (jpeg.decode(0, 0, arg))
        {
            lTime = micros() - lTime;
            char buf[80];
            sprintf(buf, "%-16s %d x %d 1/%d, decode time = %d us\n",
                    fn, jpeg.getWidth(), jpeg.getHeight(), 1 << scale, (int)lTime);
            Serial.print(buf);
        }
        jpeg.close();
    }
    delay(2000); // pause between images
    tft.endWrite(); // Not sharing TFT bus on PyPortal, just CS once and leave it
}

```

Apart from noticing the problem,  I have not studied the library code yet.
From distant memory,  the Arduino "JPEGDecoder.h" library had difficulties with odd shaped geometry.   I will have to look what I did (in the distant past).

David.

**Comment by bitbank2** [comment]
Thanks for sharing more info. I'll look at it later today. I have a feeling it has to do with my grouping of MCUs into each callback. If you set the max MCU count per call (setMaxOutputSize()) to 1, I have a feeling it will output correct images.

**Comment by prenticedavid** [comment]
The jpegDraw() function always receives "full-height" tiles even if the image has odd dimension geometry.
e.g. pDraw->iHeight is always 16 even if the bottom tiles should only be 5 high.

Please note that this corrects my sketch.   The library should pass the correct tile height in  `pDraw->iHeight`
If and when the code is corrected this "fix" will fail spectacularly.

Did your screen exhibit errors on the bottom tiles?
This would depend on the TFT controller being set to stop or wrap around a rectangular Window.
In my opinion it is safer to send the correct number of pixels.

```
int JPEGDraw(JPEGDRAW *pDraw)
{
    int w = pDraw->iWidth;
    int h = pDraw->iHeight;
    // >>> this test relies on Yoffset == 0 and fixed iHeight <<<
    if (pDraw->y == (jpeg.getHeight() & ~(h - 1))) { // odd shape tile
        h = jpeg.getHeight() % h;  //odd height
        Serial.printf("jpeg draw: @ (%d,%d) W x H = %dx%d [%dx%d]\n",
                      pDraw->x, pDraw->y, pDraw->iWidth, pDraw->iHeight, w, h);
    }
    //  Serial.printf("Pixel 0 = 0x%04x\n", pDraw->pPixels[0]);
    tft.dmaWait(); // Wait for prior writePixels() to finish
    tft.setAddrWindow(pDraw->x, pDraw->y, w, h);
    tft.writePixels(pDraw->pPixels, w * h, true, false); // Use DMA, big-endian
    return 1;
} /* JPEGDraw() */

```

I have not looked at the "blockiness" of scaled JPEGs.

David.

**Comment by prenticedavid** [comment]
Oops.   The JPEG of the grey parrots can be decoded by Picojpeg but not by tjpgd.   Although JPGDEC decodes it ok as 1/1 it does not scale it 1/2 very well.
Here is the same picture but with a different compression style.   It scales 1/2 but looks horrible (i.e. blockiness)
![bapa_80](https://user-images.githubusercontent.com/17822093/121191458-e721c680-c863-11eb-9762-f9620d92d51e.jpg)

**Comment by bitbank2** [comment]
All problems fixed - please do a git pull and confirm.
Thank you for finding these bugs. Were you using the library for something specific or just running tests to make sure it works?

**Comment by prenticedavid** [comment]
Thanks.   I was struggling to debug it on a STM32.

Chan was decoding a 16x16 tile into RGB pixels.  Using Y, Cr, Cb for each pixel
Then averaging R, G, B for the relevant scaling.   Or just selecting a single R, G, B pixel for 1/8 scale.
You seem to average Y but use a single Cr, Cb.   Which seems fine if a tile has constant Cr, Cb values.

Anyway,  it is all working nicely on 320x480 ST7796,  240x320 ILI9341, 128x160 ST7735.
The BBC2 TestCard looks ok at 1/2 size on a ST7735
Even the Parrots scale nicely.

What is heart breaking is that your fixes are so simple !!

I am impressed by how swiftly your library decodes.
I am also impressed by how good an image you get from 85% and 90% "optimisation"
Storing a photo in PROGMEM as < 32kB array means that the AVR compiler can decode several images from MEGA2560 Flash via tjpgd or PicoJpeg.   I have not tried JPEGDEC yet on an AVR.

David.

**Comment by bitbank2** [comment]
Who is Chan? Feel free to ping me in the future if you run into trouble to avoid spending too much time on any issues.
The pixel averaging I think you're referring to is for the 4:2:0 subsampled case which has 4 Y's for a single Cr/Cb anyway, so no need to average the Cr/Cb values. There are specific functions for each type of JPEG color subsampling. For 1/4 scaling I do a different DCT that's much faster and results in very good looking images. 1/8 scaling just takes the DC value from each MCU.

I optimized this code many years ago for scalar and SIMD and the same optimizations are valid on today's MCUs.

If you find an AVR with enough RAM to run this, I don't think it will perform that well because the code assumes a minimum of a 32-bit CPU. I guess it's worth a try as an intellectual exercise.

**Comment by prenticedavid** [comment]
Chan is the Author of FatFS, tjpgd and several other projects.
He lives in Japan as far as I know.

I have rendered JPEGs stored in PROGMEM on 128k Xmega,  M0, M3, M4, M7 ARM,  ESP32.

mega4809, mega2560 can render with tjpgd or picojpeg  but this was only as an academic exercise.
Not many AVRs have 8kB SRAM.   AVR struggles with maths.

David.
