### ISSUE TITLE
Please clarify in Readme whether the ESP32 bechmark uses only one or both cores

### ISSUE THREAD

**Issue by ericfont** [bitbank2/JPEGDEC#23]
The ESP32 comes with two Xtensa 32-bit LX6 microprocessors, but your Readme doesn't specify whether it is using one or both cores for the ESP32 benchmark measurement.  A quick glance at your code leads me to think it is just single threaded and so is only using one of the ESP32 cores.  But could you please specify in the readme so it is clear.

**Comment by bitbank2** [comment]
It's a single threaded implementation. There's no need to specify anything in the readme because the code will run on any target system. In order to use both cores of the ESP32, I would need to add IDF-specific code to it.
