### ISSUE TITLE
Have you done a benchmark comparison with same setup but using Espressif's esp_jpg_decode.c code on ESP32?

### ISSUE THREAD

**Issue by ericfont** [bitbank2/JPEGDEC#24]
I notice Espressif has https://github.com/espressif/esp32-camera/blob/master/conversions/esp_jpg_decode.c (https://github.com/espressif/esp32-camera/blob/master/conversions/include/esp_jpg_decode.h header) which calls https://github.com/espressif/esp32-camera/blob/master/target/esp32s2/tjpgd.c for decoding.  Have you done a comparison using your same setup but with their code?  That will help us evaluate which is better.

**Comment by bitbank2** [comment]
I did some initial testing with competing JPEG decoders (e.g. Bodmer's library) and mine averages about 50% faster. It's easy enough to set up a comparison if you're curious.
