### ISSUE TITLE
About RGB888

### ISSUE THREAD

**Issue by yiwangwuqian** [bitbank2/JPEGDEC#34]
Here is not an issue or bug.

In JPEGDEC i only could see code about RGB565, and whether support RGB888 in future?

**Comment by bitbank2** [comment]
It would not be difficult to add support for RGB888, but it will take time. My purpose in writing JPEGDEC was for microcontrollers and RGB565 SPI LCD displays. I don't have spare time to do the work right now, but it is not difficult. I can only ask you to make the change and then do a pull request.
