### ISSUE TITLE
I need help of decode jpeg

### ISSUE THREAD

**Issue by HanalogInstruments** [bitbank2/JPEGDEC#37]
Hi,
Can i use your library to decode only raw data from jpeg file without header to make it viewer?

**Comment by bitbank2** [comment]
The header of a JPEG file contains data necessary to decode the compressed image. For something like motion-jpeg (MJPEG), there are standard tables used for each frame that don't have to be sent, but normal images have potentially unique Huffman and quantization tables which need to go together with the image data. You're welcome to modify the library code to fit your needs, but it sounds like your idea about raw JPEG data may not be correct.

**Comment by HanalogInstruments** [comment]
> The header of a JPEG file contains data necessary to decode the compressed image. For something like motion-jpeg (MJPEG), there are standard tables used for each frame that don't have to be sent, but normal images have potentially unique Huffman and quantization tables which need to go together with the image data. You're welcome to modify the library code to fit your needs, but it sounds like your idea about raw JPEG data may not be correct.

How can i decode the mcu from raw data by array?

**Comment by bitbank2** [comment]
I would like to help you, but I don't understand what you're asking. Can you provide more details or a concrete example?

**Comment by HanalogInstruments** [comment]
Ah i mean to decode to get the bit like this:
![2022-06-23_125819](https://user-images.githubusercontent.com/100456607/175311699-1a4b0fbd-98e4-4a06-8c5e-5e556b29c1f5.png)
Also i want to know get width from raw data with this method:
https://arxiv.org/pdf/1410.2100.pdf

**Comment by HanalogInstruments** [comment]
> Thank you for providing that example of your intention. The tool in your screenshot above would still need the Huffman/Arithmetic tables from the JPEG header to correctly decode the compressed bits. There are standard tables that often used by encoders that you can try, but usually the data is mostly worthless without knowing the Huffman tables. You can get lucky in files with restart markers and get "anchor points" to organize the MCU layout a bit, but it would be difficult to decode correct DC/AC values without the Huffman info.

I found that when i use a same chroma sampling header from random jpeg have standard huffman coding and DQT Tables the jpeg working fine but the issue is demension from raw data not match to the header so i'm trying to find how to get width and the jpeg have algin issue

When i glue the header to raw data:

![image](https://user-images.githubusercontent.com/100456607/175342155-ab523b16-47d1-449b-9b00-90f76826608c.jpeg)

After try to change the height and width from SOF

![image](https://user-images.githubusercontent.com/100456607/175342375-c21ad7da-7527-4aa1-b6a2-56ac4a188415.jpeg)

The align issue i think when we can read the grid mcu like this so we can add how many mcu fix the mcu missing to SOS

![image](https://user-images.githubusercontent.com/100456607/175342454-08f6952e-f227-46e1-95c1-0afe73359aaa.jpeg)

Is hard to me when find: "decode jpeg mcu" on google not show any information about that

**Comment by bitbank2** [comment]
That's pretty impressive. Yes, visually you can see what the MCU alignment/width is, but doing that automatically is much harder. Something working in your favor is that digital camera images (e.g. iPhone) tend to have just a few fixed sizes, so the total MCU count can give you the info you need to know the image dimensions. Also the restart count can usually be a multiple of the MCUs per row.

**Comment by bitbank2** [comment]
I don't have any example code which does what you want. You can look at DecodeMCU() and see what you need to "feed" it, but you will need to create a valid "fast" lookup table for the AC and DC coefficients to be able to call that function. I'm sorry, but you're basically on your own.

**Comment by HanalogInstruments** [comment]
> I don't have any example code which does what you want. You can look at DecodeMCU() and see what you need to "feed" it, but you will need to create a valid "fast" lookup table for the AC and DC coefficients to be able to call that function. I'm sorry, but you're basically on your own.

I think in my case to fix the demension issue the poblem is:

https://www.disktuna.com/jpeg-visual-corruption/

Do you have any suggestion to fix the visual corruption like this?

**Comment by bitbank2** [comment]
I'm sorry, but again, I can't help you with your project beyond what I've already said.
