### ISSUE TITLE
Pure IDF fails to compile.

### ISSUE THREAD

**Issue by geiseri** [bitbank2/JPEGDEC#38]
IDF doesn't supply `Arduino.h` so it fails to compile.  It looks like if ` || defined( ESP_PLATFORM )` is added to the end of:
https://github.com/bitbank2/JPEGDEC/blob/7ac19062ee6274d69efbbccaf7105668a823f217/src/JPEGDEC.h#L16

It compiles and runs correctly.

**Comment by bitbank2** [comment]
Would you mind doing a pull request with your change?
