### ISSUE TITLE
Misconfigured idf_component_register?

### ISSUE THREAD

**Issue by acoth** [bitbank2/JPEGDEC#45]
Using in a pure idf environment, with the supplied CMakeLists, I get:
```
CMake Error at /Users/acoth/esp/esp-idf/tools/cmake/build.cmake:201 (message):
  Failed to resolve component 'jpegdec'
```
Which is fixed by changing to `REQUIRES "JPEGDEC"` instead of `REQUIRES "jpegdec"`
I am not knowledgeable enough about CMake or idf.py to know if this is a typo or serves a purpose

**Comment by bitbank2** [comment]
Martin Fasani created that CMakelists file. He puts the JPEGDEC library in a subdirectory named "jpegdec". This is why it works for him. I'm not sure why he did that, but the fix is simple.
