### ISSUE TITLE
Add SIMD support for ESP32S3

### ISSUE THREAD

**Issue by modi12jin** [bitbank2/JPEGDEC#56]
> This passage was generated by chatGPT

ESP32-S3 is a high-performance, low-power microcontroller that supports SSE (SIMD) instruction set, which can complete multiple operations in one instruction, improving code efficiency and running speed.  Here is a sample code using SIMD instructions on ESP32-S3:

 ```c
 #include "xtensa/hal.h"
 #include "esp_simd.h"
 #include <stdio.h>

 void simd_example(void)
 {
     SIMDDATA s1 = {1.0f, 2.0f, 3.0f, 4.0f};
     SIMDDATA s2 = {5.0f, 6.0f, 7.0f, 8.0f};
     SIMDDATA s3 = {0.0f, 0.0f, 0.0f, 0.0f};

     // Add the numbers in each element of s1 and s2, and store the result in s3
     s3 = SIMD_ADD(s1, s2);

     // output each element in s3
     printf("%f, %f, %f, %f\r\n", s3.f32[0], s3.f32[1], s3.f32[2], s3.f32[3]);

     // Multiply the numbers in each element of s1 and s2, and store the result in s3
     s3 = SIMDMUL(s1, s2);

     // output each element in s3
     printf("%f, %f, %f, %f\r\n", s3.f32[0], s3.f32[1], s3.f32[2], s3.f32[3]);
 }
 ```

 In this sample code, the `SIMD_ADD()` and `SIMDMUL()` functions are functions that use SIMD instructions to complete addition and multiplication operations, and the `SIMDDATA` type is a pointer, which is used to point to a vector array containing 4 floating-point number elements.  Using these functions can greatly improve code efficiency and execution speed.

 It should be noted that to use SIMD instructions on ESP32-S3, you need to include `<xtensa/hal.h>` header files and `<esp_simd.h>` header files, and use the `-msimd` option to enable SIMD instructions when compiling  set support.

**Comment by modi12jin** [comment]
https://github.com/espressif/idf-extra-components/issues/106

**Comment by bitbank2** [comment]
I'm quite familiar with SIMD coding and would be happy to optimize my code for the S3, but I can't find the include files you referenced above. Do you have a working Github link to them?

**Comment by modi12jin** [comment]
@bitbank2 Thank you for your reply, maybe the directory file name has been changed, causing the address he gave to be invalid

https://github.com/espressif/esp-adf-libs/tree/master/esp_codec/include/codec

**Comment by modi12jin** [comment]
I saw on twitter that they have introduced SIMD instructions in the technical reference manual

https://mobile.twitter.com/eMbeddedHome/status/1570520252123062274

**Comment by bitbank2** [comment]
I saw these references months ago, but no concrete examples. I thought you had new information. I'll keep searching for this info and when it actually becomes available, I'll implement it. For now, writing in ESP32 assembly language is not going to happen.

**Comment by modi12jin** [comment]
Many thanks!  Looking forward to your work.

**Comment by modi12jin** [comment]
@bitbank2 Contact Espressif's official staff, he said that the SIMD data does not seem to have a fully open version.
 There may be some clues hidden in esp-dsp.

**Comment by bitbank2** [comment]
I would honestly like to work on this, but I have very little free time. It will need to be painless and well documented.

**Comment by modi12jin** [comment]
@bitbank2 i got some replies

https://github.com/espressif/esp-bsp/issues/154

**Comment by bitbank2** [comment]
This DSP API library has been around for several years. It MAY be optimized for SIMD, but still doesn't really help any of my work.

**Comment by modi12jin** [comment]
@bitbank2 Sorry to bother you again! I got new news that this component supports SIMD.
Officials told me that this only supports whole frame decoding and cannot be divided into blocks, and if you use this, the buffer used to decode seems to need to be 32-byte aligned.

https://github.com/espressif/esp-dev-kits/tree/master/esp32-s3-lcd-ev-board%2Fexamples%2Fusb_camera_lcd%2Fcomponents%2Fesp_jpeg

**Comment by modi12jin** [comment]
Ported from ESP_ADF

**Comment by bitbank2** [comment]
Unfortunately not helpful because they didn't release the source code.

**Comment by modi12jin** [comment]
@bitbank2 Sorry to bother you again, this may not be helpful, but I wanted to tell you the test results.

JPEG decoding with SIMD, currently the whole frame, cannot be partial, there will be more in the future

> The only thing that needs attention is that the buffer must be 16-byte aligned. I tested 320*240 with a box and it took an average of 42 ms to decode RGB565. The performance on Arduino is really not good. I remember that decoding 800*480 under IDF took less than 50ms.

> JPEGDEC seems to be 68ms

https://github.com/esp-arduino-libs/ESP32_JPEG/blob/master/examples/DecodeTest/DecodeTest.ino

**Comment by bitbank2** [comment]
I worked on this over the weekend and got some good results optimizing my JPEG decoder. I'll publish the code soon.
What I find strange is your first comment on this issue - you show instructions, include files, and things that don't actually exist in the ESP32-S3 instruction set. The SIMD instructions (according to Espressif's own documentation), only support integer operations and are somewhat limited. I'm continuing my search for more info, but so far the SIMD of the S3 is mostly disappointing.

**Comment by bitbank2** [comment]
I'm not interested in someone else's closed source code.
