### ISSUE TITLE
Support loading image from HTTP

### ISSUE THREAD

**Issue by canepan** [bitbank2/JPEGDEC#63]
Hi, do you think it would be possible to read the image via the network, instead than from disk or RAM?
I would like to make [this](https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/inky_frame/inky_frame_xkcd_daily.py) work without an SD, if at all feasible

**Comment by bitbank2** [comment]
The image data can come from anywhere. You can write open/read/seek callback functions any way you want as long as the data is valid.
