### ISSUE TITLE
`JPEGDEC::openFLASH` should accept `const` pointers

### ISSUE THREAD

**Issue by oldmud0** [bitbank2/JPEGDEC#79]
The signature of `JPEGDEC::openFLASH` is as follows:

```cpp
int JPEGDEC::openFLASH(uint8_t *pData, int iDataSize, JPEG_DRAW_CALLBACK *pfnDraw)
```

This implies that `JPEGDEC::openFLASH` cannot accept `const` arrays or other `const` data. However, by definition, data located in flash is read-only, so it should accept pointers to `const` data. Thus the signature should be changed accordingly:

```cpp
int JPEGDEC::openFLASH(const uint8_t *pData, int iDataSize, JPEG_DRAW_CALLBACK *pfnDraw)
```

This also implies changing the `JPEGFILE` struct to change the `pData` field to const, but I think that would generally be a good idea to undertake as well, since this is a decoding library that only reads the data and never writes back.

For now, the workaround is to cast away the const with either `const_cast` or a C-style cast, both of which are frowned upon.

**Comment by bitbank2** [comment]
You're correct, thanks for pointing it out. I'll push a correction.
