### ISSUE TITLE
Incorrect/Striped output on ESP32-S3 with SIMD when decoding 4:2:0 images

### ISSUE THREAD

**Issue by icyqwq** [bitbank2/JPEGDEC#80]
Thanks for this amazing jpeg decode lib.
I encountered some issues while trying to use SIMD to decode JPEG images on the ESP32-S3.

Without SIMD:
![image](https://github.com/user-attachments/assets/c9a55887-713b-49f0-b82f-5266497ac777)

With SIMD:
![image](https://github.com/user-attachments/assets/f617153f-406c-4988-8577-9c8a66d31a88)

Code snippet (I'm using RGB888)
```c
  Jpeg.openFLASH((uint8_t *)src, data_length, NULL);
  Jpeg.setFramebuffer(buffer);
  Jpeg.setPixelType(RGB8888);
  int code = Jpeg.decode(0, 0, 0);
  if (code == 0) {
      LOGE(TAG, "JPEG decode error: %d", Jpeg.getLastError());
      return NULL;
  }
  Jpeg.close();
```

**Comment by icyqwq** [comment]
Based on my tests, this issue only occurs with RGB888, while RGB565 works fine.

**Comment by icyqwq** [comment]
I tested with a solid red image and printed out the pixel values of the first row. Here's what I got:
```
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FE 00 00 FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
FF 00 4A FF 
```
As you can see, every 8 pixels in each row, there are 8 incorrect values.
I suspect there might be an issue with this assembly code.
```
.rgba8888_output:          # generate RGBA 32-bit pixels
  movi.n a9,8       # shift 8 bits
  wsr.sar a9
  ee.vsl.32 q3,q3   # shift green over 8 bits
  ee.orq q7,q7,q3   # combine red and green
  ee.vcmp.eq.s16 q1,q1,q1  # create FFs
  ee.xorq q2,q2,q2  # create 00s
  ee.vzip.8 q2,q1   # create FF00 for Alpha
  ee.orq q2,q2,q6   # combine blue + alpha
  ee.vzip.16 q7,q2  # create RGB8888 pixels
  ee.vst.128.ip q7,a5,16  # store 8 x RGB8888 pixels = 32 bytes
  ee.vst.128.ip q2,a5,16
  addi.n a6,a6,-16         # restore pointer to start of 16-bit constants
  ee.vld.l.64.ip    q0,a2,0   # load right 8 Y values into Q0
  ee.movi.32.q q1,a3,0        # restore second 4 values of Cb
  ee.movi.32.q q2,a4,0        # restore second 4 values of Cr
  addi.n a8,a8,-1
  bnez.n a8,.convert_420_loop
  retw.n
```

Here's my complete test code:
```c
#include <M5Unified.h>
#include <Arduino.h>
#include "JPEGDEC.h"
#include "testjpg.cc"

extern "C" void app_main()
{
	delay(2000);

    M5.begin();
	M5.Lcd.fillScreen(GREEN);

	Jpeg.openFLASH((uint8_t *)test, sizeof(test), NULL);
	printf("JPEG Image width: %d, height: %d\n", Jpeg.getWidth(), Jpeg.getHeight());

	uint8_t* buffer = (uint8_t*)heap_caps_aligned_alloc(2, Jpeg.getWidth() * (Jpeg.getHeight() + 2) * 4, MALLOC_CAP_8BIT | MALLOC_CAP_INTERNAL);

	Jpeg.setFramebuffer(buffer);
	Jpeg.setPixelType(RGB8888);
	int code = Jpeg.decode(0, 0, 0);
	if (code == 0) {
        printf("JPEG decode error: %d\n", Jpeg.getLastError());
        return;
    }
	Jpeg.close();

	for (int i = 0; i < 128; i++) {
		printf("%02X ", buffer[i]);
		if ((i+1) % 4 == 0) {
			printf("\n");
		}
	}
	printf("\n");

	for (int y = 0; y < Jpeg.getHeight(); y++) {
		for (int x = 0; x < Jpeg.getWidth(); x++) {
			uint8_t *pixel = &buffer[(y * Jpeg.getWidth() + x) * 4];
			M5.Lcd.drawPixel(x, y, M5.Lcd.color565(pixel[0], pixel[1], pixel[2]));
		}
	}
	// M5.Lcd.pushImage(0, 0, Jpeg.getWidth(), Jpeg.getHeight(), (uint16_t*)buffer);
}

```

**Comment by bitbank2** [comment]
Thank you for discovering this bug. I found and corrected the error. The new code is pushed the repo (not released yet). Please let me know you have confirmed the fix.

**Comment by icyqwq** [comment]
Thank you for the quick fix, after testing, the new code works well :)
 I have another small question, if the buffer size for setFramebuffer is w*h*4, it causes out-of-bounds memory access. 
I took a quick look at the source code and want to confirm one thing: does the image height have to be a multiple of 8?

**Comment by bitbank2** [comment]
If you're using the S3, then the buffer needs to be a multiple of 16 bytes. For maximum speed, I write a whole Q register at a time (16 bytes).

**Comment by icyqwq** [comment]
Sorry, there was an oversight in the previous test. I tried a different image with content (not solid color), and I found that the left side is decoded incorrectly, like this:

![image](https://github.com/user-attachments/assets/1d9b885c-4170-437b-b22f-a8995bf6c861)
![image](https://github.com/user-attachments/assets/0daf5aa7-d596-4cfc-9c58-c6ab3746f436)

Test image:
![test](https://github.com/user-attachments/assets/a5915511-d964-4da7-b5e7-c331f13f76fd)
![3](https://github.com/user-attachments/assets/ed775e4a-a2a3-41ea-b4c6-9aedd8faa47d)

**Comment by bitbank2** [comment]
This is due to the image not being a multiple of 8 pixels wide. I can either force the output to have space for the extra pixels (widen the pitch) or not use the S3 SIMD in that case. Which do you prefer?

**Comment by icyqwq** [comment]
I prefer to widen th pitch.
But, the width of the second image is 200px, which is a multiple of 8, the result is still incorrect.

**Comment by bitbank2** [comment]
I should have said "MCU width" and not multiple of 8. For images with horizontal color subsampling, the MCU width is 16 and so any fraction above will cause the rest of the MCU to be written.
