### ISSUE TITLE
Issue with iWidthUsed

### ISSUE THREAD

**Issue by elan** [bitbank2/JPEGDEC#84]
**Describe the bug**

(Great library, by the way!)

I'm decoding a JPEG which is 1466 x 824, and seeing some interesting things in the write callback:

- The total size 1466 would be 256*5 + 186
- For the last chunk in the row, it passes iWidthUsed of 180 (this seems wrong, as we'd be missing 6 pixels).
- The data passed is oddly offset, I need to *skip* 6 bytes for each row (as opposed to needing to avoid the last 6 bytes as the parameter should imply).

```c++
dprintf("JPEG: Writing block at (%d, %d) with size %d x %d [%d].", pDraw->x, pDraw->y, pDraw->iWidth, pDraw->iHeight, pDraw->iWidthUsed);
```

```
JPEG: Writing block at (0, 0) with size 256 x 16 [256].
JPEG: Writing block at (256, 0) with size 256 x 16 [256].
JPEG: Writing block at (512, 0) with size 256 x 16 [256].
JPEG: Writing block at (768, 0) with size 256 x 16 [256].
JPEG: Writing block at (1024, 0) with size 256 x 16 [256].
JPEG: Writing block at (1280, 0) with size 186 x 16 [180].
```

I can't easily extract the JPEG as it's from an MPEG stream generated on the fly, but it should be reproducible as I see it with every JPEG sized this way.

Diving into the code a bit, we're setting iWidthUsed here (iPitch = 186, cx = 92, mcuCX = 16):

```c++
      if ((x+1)*mcuCX > pJPEG->iWidth) { // right edge has clipped pixels
         jd.iWidthUsed = iPitch - (cx*mcuCX - pJPEG->iWidth);
```

So this makes some sense, 92*16 =1,472 which is 6 pixels more than the actual image, but then I'd expect the last block to be:

- iWidth = 192
- iWidthUsed = 186

Let me know if I can help, I figured you might  know right away what this is 😅

**Comment by elan** [comment]
Decoding in `EIGHT_BIT_GRAYSCALE` if it makes a difference.

**Comment by elan** [comment]
FWIW, same issue in color, different block sizes:

```
JPEG: Writing block at (0, 0) with size 128 x 16 [128].
JPEG: Writing block at (128, 0) with size 128 x 16 [128].
JPEG: Writing block at (256, 0) with size 128 x 16 [128].
JPEG: Writing block at (384, 0) with size 128 x 16 [128].
JPEG: Writing block at (512, 0) with size 128 x 16 [128].
JPEG: Writing block at (640, 0) with size 128 x 16 [128].
JPEG: Writing block at (768, 0) with size 128 x 16 [128].
JPEG: Writing block at (896, 0) with size 128 x 16 [128].
JPEG: Writing block at (1024, 0) with size 128 x 16 [128].
JPEG: Writing block at (1152, 0) with size 128 x 16 [128].
JPEG: Writing block at (1280, 0) with size 128 x 16 [128].
JPEG: Writing block at (1408, 0) with size 58 x 16 [52].
```

All pixels are needed in the last block, but it tells us to ignore 6.

**Comment by bitbank2** [comment]
ok, I recreated the problem and pushed a fix. Please let me know if it resolves the issue for you.

**Comment by elan** [comment]
Thanks for the quick reply! Comparing the output for the last block for a row:

```
JPEG: Writing block at (1280, 0) with size 186 x 16 [180].
```

After:

```
JPEG: Writing block at (1280, 0) with size 186 x 16 [186].
```

The total number of pixels reported is correct now, but the image passed into the callback still seems incorrectly offset, in that the first 6 pixels in every row for that last block are garbage.

**Comment by bitbank2** [comment]
ok, I think I know what's still wrong.

**Comment by bitbank2** [comment]
ok, please try the latest code.

**Comment by elan** [comment]
Unfortunately that didn't make a difference:

- The change was to `JPEGPutMCUGray`, but in my case, the code is going through `JPEGPutMCU8BitGray`.
- Just as a side note, 3d9017bd6a8b20520594ac971e64f3a239ee22ab added a `delta` variable, but that variable is always set to zero unless I'm missing something 😅

**Comment by bitbank2** [comment]
I definitely fixed it for grayscale source images. Can you send me a sample image which shows the problem, along with the exact decoder settings you're using?

**Comment by elan** [comment]
Apologies for not being more explicit about this earlier, I'll work on getting an image, but to clarify, it's a full color image being decoded as grayscale:

```c++
    jpeg->setPixelType(EIGHT_BIT_GRAYSCALE);
    jpeg->decode(0, 0, 0);
```

**Comment by elan** [comment]
Sorry for the delay, had to port some of the MPEG-TS parsing code over to macOS to run it there. Here's a copy of a JPEG which should show the issue, when decoded into greyscale as per above.

![foo](https://github.com/user-attachments/assets/cdce997d-09e7-4c49-827e-2313b7e59900)

**Comment by elan** [comment]
Confirmed it works now, thanks so much for the fix!

**Comment by bitbank2** [comment]
You're welcome - thanks for documenting the problem.
