### ISSUE TITLE
Won't open jpg saved from GIMP

### ISSUE THREAD

**Issue by Mike4U** [bitbank2/JPEGDEC#9]
Opening and exporting an image with GIMP2.10.14 on macOS, then Exporting as jpg works everywhere as far as I know, except JPEGDEC.

Will email your demo.jpg back as demoGIMP.jpg

**Comment by bitbank2** [comment]
The JPEG in question was encoded in Progressive mode. This is not supported by JPEGDEC because it would require more RAM than is available on most embedded MCUs.
